import type { RequiredDataFromCollectionSlug } from 'payload'
import type { Media } from '@/payload-types'

type PageArgs = {
  heroImage: Media
  metaImage: Media
}

export const changspaCoursesPageData: (
  args: PageArgs,
) => RequiredDataFromCollectionSlug<'pages'> = ({ heroImage, metaImage }) => {
  return {
    slug: 'yoga-courses-at-changspa-centre',
    _status: 'published',
    hero: {
      type: 'lowImpact',
      media: heroImage.id,
    },
    layout: [
      {
        enabled: true,
        blockName: 'Content With Media',
        blockType: 'contentWithMedia',
        title: 'Yoga Courses At Changspa Centre',
        subtitle: 'Sambodhi Retreat Centre',
        content: {
          root: {
            type: 'root',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'The Mahabodhi Changspa Centre in Leh offers a variety of yoga and meditation courses designed for all levels of practitioners. Here are some of the main programs available: ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
              },
              {
                tag: 'h4',
                type: 'heading',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'Daily Yoga and Meditation Classes',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'Regular daily classes in yoga and meditation are held at the Changspa Centre, especially during the peak June–September season. These sessions include guided yoga postures, breathwork, relaxation techniques, and Buddhist Dhamma talks, creating a holistic environment for both physical and spiritual development.​',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
              },
              {
                tag: 'h4',
                type: 'heading',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'One-Month Yoga Instructor Course',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: "A comprehensive, government-recognized one-month course for those aspiring to become certified yoga instructors. The curriculum includes multi-style yoga practice, philosophy, anatomy, teaching methods, meditation, and mindfulness sessions. The course emphasizes hands-on learning and cultural immersion in Ladakh's tranquil setting, blending ancient yogic wisdom with modern instruction.​",
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
              },
              {
                tag: 'h4',
                type: 'heading',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'Drop-In and Short-Term Classes',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'Flexible drop-in yoga and meditation classes are available for travelers and residents. These sessions are tailored to provide quick relaxation, stress management, and a taste of authentic Himalayan yoga amidst serene surroundings—ideal for visitors making Leh their base.',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'These offerings help unite body, mind, and spirit within the peaceful and inspiring atmosphere of Changspa, Leh, supporting both personal growth and community wellness.',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
              },
            ],
            direction: 'ltr',
          },
        },
      },
      {
        enabled: true,
        blockName: null,
        blockType: 'contentWithMedia',
        title: 'About Changspa Centre',
        subtitle: null,
        media: null,
        content: {
          root: {
            type: 'root',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'Mahabodhi Yoga and Meditation Centre at is located at the epicentre of tourists, which is just 10 mins of walk from leh market.',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: null,
                textStyle: '',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'Ven Bhikkhu Sanghasena  always emphasis the important of spirituality and what can be more beautiful than to spread yoga to the general public as yoga not only develops physical well-being of a person but one can grow mentally, psychologically and spiritually through yoga.',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: null,
                textStyle: '',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'To the tourists, it caters a different experience as one can enjoy the real peace and nature of ladakh through yoga more beautifully.  ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: null,
                textStyle: '',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'Thus the enormous and energising yoga and mediation hall at the centre has regular sessions of yoga and meditation from timings Morning 06:00am to 10:00am, Evening 03:00pm to 07:00pm',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: null,
                textStyle: '',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'It holds different classes for beginners intermediate yoga passionates, also different classical schools of yoga such as Ashthanga, Hatha yoga Astanga vinyasa are also practised.',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: null,
                textStyle: '',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'Moreover, different yoga teachers from different parts of the world also welcome to volunteer and share their wisdom, which brings a whole new experience at the centre, where love, compassion and wisdom flourishes.',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: null,
                textStyle: '',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'The most prominent part of the week being Ven Bhikkhu Sanghasena weekly Dharma talks, as such moral talks are much needed to be spread in todays world where money matters more than morals. His word is an inspiration to all to live consciously and with a soul purpose.',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: null,
                textStyle: '',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'The ground floor also has a Mahabodhi Restaurant which serves only vegetarian local and Indian food, where the vegetables are sourced from local vegetable vendors to support local economy and made with love.',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: null,
                textStyle: '',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'The second floor accommodates paid guests,as the centre is located at a convenient location near the market it becomes more feasible for the independent guests to seek the needed service nearby.',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: null,
                textStyle: '',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'Moreover there are 3 days of yoga and meditation course held at the centre for which the guests prefers room facility, thus having rooms at the second floor serves the purpose.',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: null,
                textStyle: '',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'Changspa centre also acts as an information centre for Mahabodhi Yoga and meditation Centre choglamser.',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: null,
                textStyle: '',
                textFormat: 0,
              },
            ],
            direction: null,
          },
        },
      },
    ],
    meta: {
      description: 'Yoga Courses At Changspa Centre',
      image: heroImage.id,
      title: 'Yoga Courses At Changspa Centre',
    },
    title: 'Yoga Courses At Changspa Centre',
  }
}
