import { RequiredDataFromCollectionSlug } from 'payload'
import type { Media } from '@/payload-types'

export const NewsletterDecData = (
  mediaMap: Record<string, Media>,
): RequiredDataFromCollectionSlug<'newsletters'> => ({
  title: 'Newsletter Vol. #1: The Stillness of Winter - Dec 2025',
  slug: 'Newsletter-dec-2025',
  _status: 'published',
  heroImage: mediaMap['gallery-image6.jpg'],
  content: {
    root: {
      type: 'root',
      format: '',
      indent: 0,
      version: 1,
      children: [
        {
          tag: 'h2',
          type: 'heading',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Winter Solstice: Embracing the Dark to Find the Light',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'December brings us to the Winter Solstice, the shortest day and longest night of the year. In the high-altitude desert of Ladakh, this transition is felt deeply as the landscape becomes a silent, snowy white. It is a time for deep rest and introspection. Just as the Earth lies fallow in preparation for the coming spring, we too must allow our minds and bodies a period of quietude. In the silence of winter, we can hear the whispers of our own soul more clearly.',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          textStyle: '',
          textFormat: 0,
        },
        {
          tag: 'h3',
          type: 'heading',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Year-End Reflection and Letting Go',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'As 2025 draws to a close, we invite you to reflect on your journey. What have you learned? What are you ready to release? This month, our meditation sessions will focus on the practice of "Aparigraha" or non-attachment. By letting go of what no longer serves us—be it old grudges, limiting beliefs, or physical clutter—we create space for the infinite possibilities of the new year.',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
          textStyle: '',
          textFormat: 0,
        },
        {
          tag: 'h3',
          type: 'heading',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Winter Solstice Peace Prayer',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'On December 21st, the MIMC community will gather for a global peace prayer. We will chant the Maha Mrityunjaya Mantra for the health and well-being of all sentient beings. We encourage you to join us from wherever you are in the world. Set aside 15 minutes at dawn or dusk to sit in silence and radiate thoughts of peace and harmony to all corners of the Earth.',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
          textStyle: '',
          textFormat: 0,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Winter Practices for Inner Warmth:',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
          textStyle: '',
          textFormat: 0,
        },
        {
          tag: 'ul',
          type: 'list',
          start: 1,
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              type: 'listitem',
              value: 1,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Restorative Yoga to soothe the nervous system.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              type: 'listitem',
              value: 2,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Pranayama (specifically Surya Bhedana) to increase internal vitality.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              type: 'listitem',
              value: 3,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Abhyanga (self-massage with warm oil) to protect the skin and calm the mind.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
          ],
          listType: 'bullet',
          direction: null,
        },
      ],
      direction: 'ltr',
    },
  },
  predesignedPDF: mediaMap['jan-2026.pdf'],
})
