import { RequiredDataFromCollectionSlug } from 'payload'
import type { Media } from '@/payload-types'

export const NewsletterOctData = (
  mediaMap: Record<string, Media>,
): RequiredDataFromCollectionSlug<'newsletters'> => ({
  title: 'Newsletter Vol. #1: Harvest of the Heart - Oct 2025',
  slug: 'Newsletter-oct-2025',
  _status: 'published',
  heroImage: mediaMap['gallery-image4.jpg'],
  content: {
    root: {
      type: 'root',
      format: '',
      indent: 0,
      version: 1,
      children: [
        {
          tag: 'h2',
          type: 'heading',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'The Harvest Season: Cultivating Gratitude',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'As the autumn leaves begin to fall and the air turns crisp in the valleys of Ladakh, we find ourselves in a season of harvest. This is not just a time for gathering crops, but a sacred opportunity to harvest the fruits of our internal practice. Throughout the year, we have planted seeds of intention, watered them with discipline, and now, we pause to acknowledge the growth within our hearts and minds.',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          textStyle: '',
          textFormat: 0,
        },
        {
          tag: 'h3',
          type: 'heading',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Autumn Equinox and the Path of Balance',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'The equinox reminds us that balance is not a static state but a dynamic dance. In our yoga practice this month, we focus on grounding asanas that connect us to the Earth while allowing our spirits to soar. We invite you to join our daily sessions at the Sambodhi Retreat Centre, where the mountains themselves offer a lesson in steadfastness.',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
          textStyle: '',
          textFormat: 0,
        },
        {
          tag: 'h3',
          type: 'heading',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Special Workshop: Traditional Ladakhi Wisdom',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Coming up on October 15th, we are hosting a unique gathering with local elders to discuss the intersection of traditional Himalayan lifestyle and modern mindfulness. We will explore how the concept of "Sustenance" goes beyond food to include spiritual nourishment and community resilience.',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
          textStyle: '',
          textFormat: 0,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Topics will include:',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
          textStyle: '',
          textFormat: 0,
        },
        {
          tag: 'ul',
          type: 'list',
          start: 1,
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              type: 'listitem',
              value: 1,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Seasonal eating according to Sowa Rigpa (Traditional Tibetan Medicine)',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              type: 'listitem',
              value: 2,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'The role of community chanting in building mental strength',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              type: 'listitem',
              value: 3,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Mindful preparation for the long Himalayan winter',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
          ],
          listType: 'bullet',
          direction: null,
        },
      ],
      direction: 'ltr',
    },
  },
  predesignedPDF: mediaMap['jan-2026.pdf'],
})
