import { RequiredDataFromCollectionSlug } from 'payload'
import type { Media } from '@/payload-types'

export const NewsletterJanData = (
  mediaMap: Record<string, Media>,
): RequiredDataFromCollectionSlug<'newsletters'> => ({
  title: 'Newsletter Vol. #1: New Beginnings and Clear Intentions - Jan 2026',
  slug: 'Newsletter-jan-2026',
  _status: 'published',
  heroImage: mediaMap['sambodhi.jpg'],
  content: {
    root: {
      type: 'root',
      format: '',
      indent: 0,
      version: 1,
      children: [
        {
          tag: 'h2',
          type: 'heading',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Stepping into the New Year with Sankalpa',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Welcome to 2026! As the calendar turns, we are presented with a fresh canvas. In the yogic tradition, we move beyond "resolutions" and embrace the practice of Sankalpa—a heart-felt intention that aligns with our highest truth. A Sankalpa is not something we struggle to achieve, but a seed we plant in the fertile soil of our subconscious. This month, we focus on clarity, purpose, and the gentle discipline required to nurture our spiritual growth.',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          textStyle: '',
          textFormat: 0,
        },
        {
          tag: 'h3',
          type: 'heading',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'International Festival of Yoga & Meditation 2026',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'We are officially opening registrations for our flagship event! Celebrate the 12th UN International Day of Yoga in the breathtaking Himalayas. This year’s theme is "Global Harmony through Personal Peace." Join world-renowned teachers and seekers from over 50 countries for a week of transformative practice and community building.',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
          textStyle: '',
          textFormat: 0,
        },
        {
          tag: 'h3',
          type: 'heading',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'The Power of Silence: A 7-Day Residential Retreat',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Starting January 20th, we are offering an intensive silent meditation retreat at the Sambodhi Centre. This program is designed for those who wish to go deep into the layers of their mind. Through Noble Silence, we learn to observe our thoughts without judgment and discover the profound peace that lies beneath the noise of daily life.',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
          textStyle: '',
          textFormat: 0,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'January Curriculum Highlights:',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
          textStyle: '',
          textFormat: 0,
        },
        {
          tag: 'ul',
          type: 'list',
          start: 1,
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              type: 'listitem',
              value: 1,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Introduction to Yoga Nidra for deep relaxation and Sankalpa planting.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              type: 'listitem',
              value: 2,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Asana sequences for detoxifying the body after the holidays.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              type: 'listitem',
              value: 3,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Daily Buddhist philosophy talks on "The Nature of Mind."',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
          ],
          listType: 'bullet',
          direction: null,
        },
      ],
      direction: 'ltr',
    },
  },
  predesignedPDF: mediaMap['jan-2026.pdf'],
})
