import { RequiredDataFromCollectionSlug } from 'payload'
import type { Media } from '@/payload-types'

export const NewsletterFebData = (
  mediaMap: Record<string, Media>,
): RequiredDataFromCollectionSlug<'newsletters'> => ({
  title: 'Newsletter Vol. #1: Mindfulness in Daily Life - Feb 2026',
  slug: 'Newsletter-feb-2026',
  _status: 'published',
  heroImage: mediaMap['gallery-image7.jpg'],
  content: {
    root: {
      type: 'root',
      format: '',
      indent: 0,
      version: 1,
      children: [
        {
          tag: 'h2',
          type: 'heading',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Mindfulness Beyond the Mat',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'As winter continues to hold the Himalayas in its quiet embrace, we invite you to explore the practice of mindfulness not just during your formal sessions, but in every moment of your day. Whether you are walking, eating, or working, the essence of yoga is to remain present and aware. This "off-the-mat" practice is where the true transformation happens, as we learn to respond rather than react to the world around us.',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          textStyle: '',
          textFormat: 0,
        },
        {
          tag: 'h3',
          type: 'heading',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Winter Meditation Retreat: Finding Inner Warmth',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Our recent silent retreat at the Sambodhi Centre was a profound journey into stillness. We are deeply grateful to all the participants who joined us in braving the sub-zero temperatures to find their inner warmth. Through shared silence and group practice, we realized that the heart’s compassion is the ultimate shield against any cold.',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
          textStyle: '',
          textFormat: 0,
        },
        {
          tag: 'h3',
          type: 'heading',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Tip of the Month: Mindful Breathing in Stressful Moments',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Take three deep breaths whenever you feel overwhelmed. Notice the cool air entering your nostrils and the warm air leaving your body. This simple act of conscious breathing anchors you back to the present moment and creates a "gap" between a stimulus and your response. In that gap lies your freedom.',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
          textStyle: '',
          textFormat: 0,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'February Community Focus:',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
          textStyle: '',
          textFormat: 0,
        },
        {
          tag: 'ul',
          type: 'list',
          start: 1,
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              type: 'listitem',
              value: 1,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Metta (Loving-Kindness) meditation for global healing.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              type: 'listitem',
              value: 2,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Supporting our local animal sanctuary during the peak of winter.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              type: 'listitem',
              value: 3,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Mindful tea ceremonies to appreciate the beauty in small things.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
          ],
          listType: 'bullet',
          direction: null,
        },
      ],
      direction: 'ltr',
    },
  },
  predesignedPDF: mediaMap['jan-2026.pdf'],
})
