import { RequiredDataFromCollectionSlug } from 'payload'
import type { Media } from '@/payload-types'

export const NewsletterNovData = (
  mediaMap: Record<string, Media>,
): RequiredDataFromCollectionSlug<'newsletters'> => ({
  title: 'Newsletter Vol. #1: Illuminating the Inner Path - Nov 2025',
  slug: 'Newsletter-nov-2025',
  _status: 'published',
  heroImage: mediaMap['gallery-image5.jpg'],
  content: {
    root: {
      type: 'root',
      format: '',
      indent: 0,
      version: 1,
      children: [
        {
          tag: 'h2',
          type: 'heading',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Kindling the Light Within',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'As the days grow shorter and the nights stretch longer, many traditions around the world celebrate the triumph of light over darkness. In our spiritual practice, this external transition serves as a powerful metaphor. When the world outside becomes dim, we are called to go inward and rediscover the unextinguishable flame of awareness that resides in each of us. This inner light—Prakash—is our true nature, and meditation is the art of clearing the soot of distraction from the glass of our souls.',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          textStyle: '',
          textFormat: 0,
        },
        {
          tag: 'h3',
          type: 'heading',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'The Festival of Lights: A Yogic Perspective',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Diwali and other festivals of light remind us that every candle we light externally is a commitment to brightening our internal world. This month, our workshops will focus on Trataka (candle-gazing meditation), a practice designed to improve concentration and awaken the "third eye" or Ajna Chakra. By focusing our gaze, we learn to still the restless mind and perceive the subtle vibrations of peace.',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
          textStyle: '',
          textFormat: 0,
        },
        {
          tag: 'h3',
          type: 'heading',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Community Update: The Mahabodhi International School',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'We are thrilled to report that our students have successfully completed their autumn term. Education is the greatest light we can provide, and through your generous support, we continue to offer holistic education to children from some of the most remote regions of the Himalayas. We invite you to read the full report on our website about how we integrate mindfulness into the daily curriculum of our young learners.',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
          textStyle: '',
          textFormat: 0,
        },
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              mode: 'normal',
              text: 'Practical Tips for Staying Vibrant in November:',
              type: 'text',
              style: '',
              detail: 0,
              format: 0,
              version: 1,
            },
          ],
          direction: null,
          textStyle: '',
          textFormat: 0,
        },
        {
          tag: 'ul',
          type: 'list',
          start: 1,
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              type: 'listitem',
              value: 1,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Early Morning Sun Salutations to absorb the limited daylight.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              type: 'listitem',
              value: 2,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Warm ginger and tulsi tea to maintain internal heat.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              type: 'listitem',
              value: 3,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Evening gratitude journaling to acknowledge the blessings of the day.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
          ],
          listType: 'bullet',
          direction: null,
        },
      ],
      direction: 'ltr',
    },
  },
  predesignedPDF: mediaMap['jan-2026.pdf'],
})
